version: '3'

services:
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./laravel:/var/www:z
      - ./nginx/conf.d:/etc/nginx/conf.d:z
      - ./logs:/var/log/nginx:z
    env_file:
      - .env
    ports:
      - "$PROJECT_PORT:80"
    tty:  true
    
    restart: unless-stopped
    depends_on:
      - cryptopro
    container_name: $NGINX_NAME

  cryptopro:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROOT_CA: $ROOT_CA
        PHP_URL: $PHP_URL
    tty:  true
    env_file:
      - .env
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./laravel:/var/www:z
    container_name: $CPRO_NAME

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.ws
    ports:
      - $WEBSOCKET_PORT:6001
    restart: unless-stopped
    volumes:
      - ./laravel:/var/www:z
    depends_on:
      - cryptopro
    container_name: $WS_NAME